name: dataisdelicious
favicon: null
layout_spectrum: 0.28566
typography_spectrum: 0.65383
title: dataisdelicious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#454545'
    - '#a6a6a6'
    - '#7c7c7c'
    - '#ed000f'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
