name: dataisdelicious
favicon: null
layout_spectrum: 0.8711074909660965
typography_spectrum: 0.7610028518829495
title: dataisdelicious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#e86426'
    - '#58bae9'
    - '#477a92'
    - '#5f3e2d'
  brandStrength: 0.024876023875549436
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
